apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-demo.fullname" . }}
  labels:
    {{- include "helm-demo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    name: {{ .Values.service.portnamesder }}
  selector:
    {{- include "helm-demo.selectorLabels" . | nindent 6 }}
